### ISSUE TITLE
Unable to build: no type named 'lock_guard' in namespace 'std'

### ISSUE THREAD

**Issue by guillaumerosinosky** [lazypoline/lazypoline#1]
Hello,

I'm trying to build lazypoline on Ubuntu 24.04, but std:lock_guard is missing. Maybe it's something obvious missing from my installation. 
![image](https://github.com/lazypoline/lazypoline/assets/10268636/a2958d37-2d6e-4ee7-abf7-da23a60bfc57)

I have tried to add "#include \<mutex\>" in the files, but of course it is not available in freestanding mode so I guess you have another way to do it. 

Do you have an idea on this? Or could you give more details about your build environment

Thanks a lot :)

**Comment by adriaanjacobs** [comment]
Multiple people seem to face this issue on 24.04. We're working on a proper fix, if you've found something in the mean time, let us know!
